baseURL = 'https://jerossas.github.io/dunnwr/'
languageCode = 'es-co'
title = 'Dunnwr'

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Blog"
        url = "/blog/"
        weight = 2

    [[menu.main]]
        name = "Learning"
        url = "/learning/"
        weight = 3

    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 4

[markup]
    [markup.goldmark]
        [markup.goldmark.parser]
            wrapStandAloneImageWithinParagraph = false

